/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-12-17 16:32:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.seat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import seat.*;

public final class userSeat_005fAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("seat");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>사용자 자리 관리자모드view</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/manageView.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/earlyaccess/hanna.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	ServletContext sc = getServletContext();
 	ArrayList<seatUserBean> seatList = seatDButil.getSeatUserList(sc);
 	String name[] = new String[5];
 	String time[] = new String[5];
 	int seat_id[] = new int[5];
 	for(int i=0; i<seatList.size(); i++){
 		seatUserBean seatUser = seatList.get(i);
 		name[i] = seatUser.getName();
 		time[i] = seatUser.getTime();
 		seat_id[i] = seatUser.getSeat_id()-1;
 	}	
	
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<div class=\"nav-header\">\r\n");
      out.write("    <div class=\"nav-brand\">\r\n");
      out.write("    <i class=\"fa fa-bars fa-3x\"></i>\r\n");
      out.write("    <div class=\"header-links\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li data-menuanchor=\"thirdPage\"><a href=\"../login/logoutAction.jsp\">LOGOUT</a></li>\r\n");
      out.write("        <li data-menuanchor=\"secondPage\"><a href=\"../food/food_main_Admin.jsp\">MENU</a></li>\r\n");
      out.write("        <li data-menuanchor=\"firstPage\"><a href=\"../user/memberList.jsp\">USER INFO</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- partial:index.partial.html -->\r\n");
      out.write("<div id=\"app-cover\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"toggle-button-cover\">\r\n");
      out.write("      <div class=\"button-cover\">\r\n");
      out.write("        <div class=\"button r\" id=\"button-1\" >\r\n");
      out.write("          <div class=\"knobs\"></div>\r\n");
      out.write("          <div class=\"layer\">\r\n");
      out.write("         <div class=\"0\" style=\"text-align:center;padding-top:10px;\">00:00:00</div>\r\n");
      out.write("         <div id=\"0-state\" style=\"text-align:center;padding-top:3px;padding-bottom:10px;\">사용중</div>\r\n");
      out.write("         <div id=\"0-user\" style=\"padding-left:15px; font-size:20px; color:#708090; padding-bottom:10px;\"> </div>\r\n");
      out.write("         <div class=\"0buttons\" style=\"top:20%; padding-left:17px; \">         \r\n");
      out.write("         <input type=\"button\" style=\"background:#80C4DE; margin:5px;color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\"onclick=\"fncAddTime(0,3600, 1);\" value=\"한시간추가\"/>   \r\n");
      out.write("         <input type=\"button\" style=\"background:#80C4DE; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\"onclick=\"fncAddTime(0,7200, 1);\" value=\"두시간추가\"/>\r\n");
      out.write("         <input type=\"button\" style=\"background:#EA575B; margin-left:50px; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:10px;\"onclick=\"fucEndTimer(0);\" value=\"사용종료\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("          </div>\r\n");
      out.write("             \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"toggle-button-cover\">\r\n");
      out.write("      <div class=\"button-cover\">\r\n");
      out.write("        <div class=\"button r\" id=\"button-2\">\r\n");
      out.write("          <div class=\"knobs\"></div>\r\n");
      out.write("             <div class=\"layer\">\r\n");
      out.write("                <div class=\"1\" style=\"text-align:center;padding-top:10px;\">00:00:00</div>\r\n");
      out.write("                <div id=\"1-state\" style=\"text-align:center;padding-top:3px;padding-bottom:10px;\">사용중</div>\r\n");
      out.write("                <div id=\"1-user\" style=\"padding-left:5px; font-size:20px; color:#708090; padding-bottom:10px;\"> </div>\r\n");
      out.write("                <div class=\"1buttons\" style=\"top:20%; padding-left:17px; \">      \r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; margin:5px;color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\"onclick=\"fncAddTime(1,3600, 2);\" value=\"한시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\" onclick=\"fncAddTime(1,7200, 2);\" value=\"두시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#EA575B; margin-left:50px; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:10px;\" onclick=\"fucEndTimer(1);\" value=\"사용종료\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"toggle-button-cover\">\r\n");
      out.write("      <div class=\"button-cover\">\r\n");
      out.write("        <div class=\"button r\" id=\"button-3\">\r\n");
      out.write("          <div class=\"knobs\"></div>\r\n");
      out.write("          <div class=\"layer\">\r\n");
      out.write("             <div class=\"2\" style=\"text-align:center;padding-top:10px;\">00:00:00</div>\r\n");
      out.write("                <div id=\"2-state\" style=\"text-align:center;padding-top:3px;padding-bottom:10px;\">사용중</div>\r\n");
      out.write("                <div id=\"2-user\" style=\"padding-left:5px; font-size:20px; color:#708090; padding-bottom:10px;\"> </div>\r\n");
      out.write("                <div class=\"2buttons\" style=\"top:20%; padding-left:17px; \">      \r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; margin:5px;color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\"onclick=\"fncAddTime(2,3600, 3);\" value=\"한시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\" onclick=\"fncAddTime(2,7200, 3);\" value=\"두시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#EA575B; margin-left:50px; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:10px;\" onclick=\"fucEndTimer(2);\" value=\"사용종료\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"toggle-button-cover\">\r\n");
      out.write("      <div class=\"button-cover\">\r\n");
      out.write("        <div class=\"button r\" id=\"button-4\">\r\n");
      out.write("          <div class=\"knobs\"></div>\r\n");
      out.write("          <div class=\"layer\">\r\n");
      out.write("          <div class=\"3\" style=\"text-align:center;padding-top:10px;\">00:00:00</div>\r\n");
      out.write("                <div id=\"3-state\" style=\"text-align:center;padding-top:3px;padding-bottom:10px;\">사용중</div>\r\n");
      out.write("                <div id=\"3-user\" style=\"padding-left:5px; font-size:20px; color:#708090; padding-bottom:10px;\"> </div>\r\n");
      out.write("                <div class=\"3buttons\" style=\"top:20%; padding-left:17px; \">      \r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; margin:5px;color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\"onclick=\"fncAddTime(3,3600, 4);\" value=\"한시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\" onclick=\"fncAddTime(3,7200, 4);\" value=\"두시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#EA575B; margin-left:50px; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:10px;\" onclick=\"fucEndTimer(3);\" value=\"사용종료\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"toggle-button-cover\">\r\n");
      out.write("      <div class=\"button-cover\">\r\n");
      out.write("        <div class=\"button r\" id=\"button-5\">\r\n");
      out.write("          <div class=\"knobs\"></div>\r\n");
      out.write("          <div class=\"layer\">\r\n");
      out.write("             <div class=\"4\" style=\"text-align:center;padding-top:10px;\">00:00:00</div>\r\n");
      out.write("                <div id=\"4-state\" style=\"text-align:center;padding-top:3px;padding-bottom:10px;\">사용중</div>\r\n");
      out.write("                <div id=\"4-user\" style=\"padding-left:5px; font-size:20px; color:#708090; padding-bottom:10px;\"> </div>\r\n");
      out.write("                <div class=\"1buttons\" style=\"top:20%; padding-left:17px; \">      \r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; margin:5px;color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\"onclick=\"fncAddTime(4,3600, 5);\" value=\"한시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#80C4DE; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:9px;\" onclick=\"fncAddTime(4,7200, 5);\" value=\"두시간추가\"/>\r\n");
      out.write("            <input type=\"button\" style=\"background:#EA575B; margin-left:50px; color:#fff;border:none; font-family:'Hanna', sans-serif;padding:10px;\" onclick=\"fucEndTimer(4);\" value=\"사용종료\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- partial -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar handler = new Array();\r\n");
      out.write("\t\tvar leftT = new Array();\r\n");
      out.write("       \r\n");
      out.write("\t\tvar time1 = \"");
      out.print(time[0]);
      out.write("\"*1;\r\n");
      out.write("\t\tvar time2 = \"");
      out.print(time[1]);
      out.write("\"*1;\r\n");
      out.write("\t\tvar time3 = \"");
      out.print(time[2]);
      out.write("\"*1;\r\n");
      out.write("\t\tvar time4 = \"");
      out.print(time[3]);
      out.write("\"*1;\r\n");
      out.write("\t\tvar time5 = \"");
      out.print(time[4]);
      out.write("\"*1;\r\n");
      out.write("   \r\n");
      out.write("\t\tvar name1 = \"");
      out.print(name[0]);
      out.write("\";\r\n");
      out.write("\t\tvar name2 = \"");
      out.print(name[1]);
      out.write("\";\r\n");
      out.write("\t\tvar name3 = \"");
      out.print(name[2]);
      out.write("\";\r\n");
      out.write("\t\tvar name4 = \"");
      out.print(name[3]);
      out.write("\";\r\n");
      out.write("\t\tvar name5 = \"");
      out.print(name[4]);
      out.write("\";\r\n");
      out.write("   \r\n");
      out.write("\t\tvar seat1 = \"");
      out.print(seat_id[0]);
      out.write("\";\r\n");
      out.write("\t\tvar seat2 = \"");
      out.print(seat_id[1]);
      out.write("\";\r\n");
      out.write("\t\tvar seat3 = \"");
      out.print(seat_id[2]);
      out.write("\";\r\n");
      out.write("\t\tvar seat4 = \"");
      out.print(seat_id[3]);
      out.write("\";\r\n");
      out.write("\t\tvar seat5 = \"");
      out.print(seat_id[4]);
      out.write("\";\r\n");
      out.write("       \r\n");
      out.write("\t       /* Timer */\r\n");
      out.write("\t       function countdown(className, seconds, user){\r\n");
      out.write("\t          var tnum = className; //타이머 번호\r\n");
      out.write("\t          var element,stateName,userName,endTime, hours, mins, secs, msLeft, time;\r\n");
      out.write("\t          \r\n");
      out.write("\t          stateName = className.concat(\"-state\");\r\n");
      out.write("\t          userName = className.concat(\"-user\");\r\n");
      out.write("\t         var sUser = String(user);\r\n");
      out.write("\t          function updateTimer(){\r\n");
      out.write("\t                      msLeft = endTime - (+new Date);\r\n");
      out.write("\t                      if ( msLeft < 0 ) { // 시간 초과시 이벤트 영역\r\n");
      out.write("\t                         stateName = className.concat(\"-state\");\r\n");
      out.write("\t                         document.getElementById(stateName).innerHTML = '빈좌석';\r\n");
      out.write("\t                         document.getElementById(userName).innerHTML = ' ';\r\n");
      out.write("\t                      }\r\n");
      out.write("\t                      else {\r\n");
      out.write("\t                         document.getElementById(stateName).innerHTML = '사용중';//빈좌석을 사용중으로 변경 후 \r\n");
      out.write("\t                         document.getElementById(userName).innerHTML = sUser ; //사용자 이름을 표기\r\n");
      out.write("\t                              time = new Date( msLeft );\r\n");
      out.write("\t                              leftT[tnum] = msLeft; //현재 남은 시간을 전역으로 추가\r\n");
      out.write("\t                              hours = ('0' + time.getUTCHours()).slice(-2);\r\n");
      out.write("\t                              mins  = ('0' + time.getUTCMinutes()).slice(-2);\r\n");
      out.write("\t                              secs  = ('0' + time.getUTCSeconds()).slice(-2);\r\n");
      out.write("\t                              element.innerHTML = hours + ':' + mins + ':' + secs;\r\n");
      out.write("\t                              handler[tnum] = setTimeout(updateTimer, time.getUTCMilliseconds());\r\n");
      out.write("\t                      }\r\n");
      out.write("\t               }\r\n");
      out.write("\t               element = document.getElementsByClassName(className);\r\n");
      out.write("\t               if(element.length!=0) {// 해당 타이머가 맞는지 확인\r\n");
      out.write("\t                      element = element[0];\r\n");
      out.write("\t                      endTime = (+new Date) + 1000 * seconds;\r\n");
      out.write("\t                      updateTimer(); // 타이머 실행\r\n");
      out.write("\t                      \r\n");
      out.write("\t               } else { //해당 타이머가 아니면...\r\n");
      out.write("\t                      //alert(\"no timer\");\r\n");
      out.write("\t               }\r\n");
      out.write("\t       }\r\n");
      out.write("\t       \r\n");
      out.write("\t       \r\n");
      out.write("\t       fncLoadTimer();\r\n");
      out.write("\r\n");
      out.write("\tfunction fncAddTime(tableNum, time, number) { //버튼 클릭\r\n");
      out.write("\t         clearTimeout(handler[tableNum]);\r\n");
      out.write("\t            tleft = leftT[tableNum] / 1000;\r\n");
      out.write("\t            timerName = String(tableNum);\r\n");
      out.write("\t            if(number==1){\r\n");
      out.write("\t            \tcountdown(timerName,tleft + time, name1);\r\n");
      out.write("\t            }else if(number==2){\r\n");
      out.write("\t            \tcountdown(timerName,tleft + time, name2);\r\n");
      out.write("\t            }else if(number==3){\r\n");
      out.write("\t            \tcountdown(timerName,tleft + time, name3);\r\n");
      out.write("\t            }else if(number==4){\r\n");
      out.write("\t            \tcountdown(timerName,tleft + time, name4);\r\n");
      out.write("\t            }else{\r\n");
      out.write("\t            \tcountdown(timerName,tleft + time, name5);\r\n");
      out.write("\t            }\r\n");
      out.write("\t         \r\n");
      out.write("\t}\r\n");
      out.write("\t  \r\n");
      out.write("\tfunction fncLoadTimer() { //페이지 최초 실행시 db에서 불러오기\t\r\n");
      out.write("\t   \tcountdown(seat1, time1, name1);  // seconds 로 생성  사용자 이름\r\n");
      out.write("\t   \tcountdown(seat2, time2, name2);\r\n");
      out.write("\t   \tcountdown(seat3, time3, name3);\r\n");
      out.write("\t   \tcountdown(seat4, time4, name4);\r\n");
      out.write("\t   \tcountdown(seat5, time5, name5);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction fucEndTimer(timernum){ //사용종료\r\n");
      out.write("\t   clearTimeout(handler[timernum]);\r\n");
      out.write("\t   timerName = String(timernum);\r\n");
      out.write("\t   countdown(timerName,0);\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
